[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "df_csv_excel"
authors = [{name = "LeZhang", email = "zhanglenus@gmail.com"}]
dynamic = ["version", "description"]
